import AppKit
import Foundation
import Observation

@MainActor
@Observable
final class ClipboardController {
    let store: ClipboardStore

    var isEnabled: Bool { settings.clipboardEnabled }

    private let settings: SettingsStore
    private var pollTask: Task<Void, Never>?
    private var lastChangeCount = 0
    private var targetApp: NSRunningApplication?
    private var activationObserver: NSObjectProtocol?

    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init(settings: SettingsStore, store: ClipboardStore = ClipboardStore()) {
        self.settings = settings
        self.store = store
    }

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        rememberFrontmostApp()
        observeActivations()
        pollTask?.cancel()
        pollTask = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                self?.poll()
                try? await Task.sleep(for: .milliseconds(400))
            }
        }
    }

    func stop() {
        pollTask?.cancel()
        pollTask = nil
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
            self.activationObserver = nil
        }
    }

    func ignoreCurrentPasteboard() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func rememberFrontmostApp() {
        noteActivation(NSWorkspace.shared.frontmostApplication)
    }

    func recordCopiedText(_ text: String) {
        guard settings.clipboardEnabled else { return }
        store.record(text)
    }

    func copy(_ item: ClipboardItem) {
        store.copy(item)
        ignoreCurrentPasteboard()
        recordCopiedText(item.text)
    }

    func insert(_ item: ClipboardItem) async -> InsertResult {
        let result = await TextInserter.insert(item.text, into: resolvedTarget())
        if result == .copied {
            recordCopiedText(item.text)
        }
        return result
    }

    private func resolvedTarget() -> NSRunningApplication? {
        if let targetApp, !targetApp.isTerminated,
           targetApp.bundleIdentifier != Bundle.main.bundleIdentifier {
            return targetApp
        }
        rememberFrontmostApp()
        return targetApp
    }

    private func observeActivations() {
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
        }
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] notification in
            let app = notification.userInfo?[NSWorkspace.applicationUserInfoKey] as? NSRunningApplication
            Task { @MainActor in
                self?.noteActivation(app)
            }
        }
    }

    private func noteActivation(_ app: NSRunningApplication?) {
        guard let app, app.bundleIdentifier != Bundle.main.bundleIdentifier else { return }
        targetApp = app
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        guard settings.clipboardEnabled else { return }

        let types = pasteboard.types ?? []
        if types.contains(Self.concealedType)
            || types.contains(Self.transientType)
            || types.contains(Self.autoGeneratedType) {
            return
        }
        guard let text = pasteboard.string(forType: .string) else { return }
        store.record(text)
    }
}
